[package]
name = "aoc-2020-rust"
version = "0.1.0"
authors = ["Adrian Opsahl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parse-display = "0.4"
regex = "1"
lazy_static = "1.4.0"
thiserror = "1.0"